---
title: "Conclusion"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We found that the tweets from Obama’s account were more likely to be created from a desktop or laptop computer compared to the tweets from Kanye’s account which were from an iPhone. This may, in part, explain why we also found that Obama was more likely to tweet between 11am and 3pm - within standard work hours - compared to the greater variability in the timing of tweets from Kanye. It is also important to note that, as a performer, Kanye may be working late at night (i.e. when concerts tend to occur) which may also explain why his tweet behavior looks differently than someone like Obama who may, along with his staffers, work closer to the conventional work day. Finally, it is important to note that both Kanye and Obama likely travel often, leading to variability in the time zones in which they make tweets. This is a weakness of looking at when tweets are made in EST since the increase in Kanye’s tweet time variability may reflect more frequent travel rather than a meaningful difference in which tweets are made. Nonetheless, although this may not directly measure the hour at which each of them tweet, this may still be a useful input in our model to predict which tweets belong to whom.

We also found that Obama’s tweets conveyed more emotion compared to Kanye’s. This may not be particularly surprising as Obama and Kanye may be tweeting to different audiences and have different pressures when crafting their tweets. It is also possible that Obama’s tweets are registered as being more emotive as it may be considered inappropriate or risky for him to use more complex language, like sarcasm. As someone in office, he likely had to be careful that his tweets were literal so that they were less likely to be misconstrued by the public which would then make it easier to associate his tweets with specific emotions. Kanye may not face quite as much public scrutiny as an entertainer, so he may use language that is considered to be more neutral by the NRC algorithm or use more sarcastic language. There may also be less pressure on Kanye to relate or empathize with his twitter audience whereas there may be more of an expectation for a president to do so. This raises an interesting question if Kanye’s sentiment levels changed following his announcement that he would run for president (although, not every politician conforms to society’s expectations of presidential conduct). 

As noted above, our model has an AUC of .9, indicating that there is a 90% chance that any given tweet will be correctly diagnosed as either Obama’s or Kanye’s. Further, the model’s true positive rate and true negative rate are both about .85, indicating that our model has strong predictive power. When we tried our prediction algorithm on a third user’s tweets (Drake’s), it overwhelmingly classified his tweets as having originated from Kanye’s account. This is not very surprising, given that Kanye and Drake are entertainers of a similar (43 vs. 34) age. 

Overall, we feel that our predictive model does an impressive job of classifying tweet origin. Barack Obama and Kanye West are both African American men with a significant cultural impact. Yet, it is unsurprising that they tweet in different ways, considering their difference in personal characteristics, backgrounds, and primary audiences. Nonetheless, it is noteworthy that those differences can be ascertained by our model and put to use on test data. 
