---
title: "Introduction"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Although they achieved fame in different ways, Kanye West and Barack Obama are two of the most influential people of our time. Kanye West has amassed over 30 million followers, mostly from his incredibly successful entertainment career and relationship with mega-socialite family, the Kardashians, but has also received recent attention for his most recent foray into the world of politics as a 2020 candidate running on a conservative platform. On the other hand, Barack Obama established his prominence as an American politician and lawyer. He served as the 44th president of the United States, serving from 2008-2016, and was the first African-American president of the U.S. He is a member of the Democratic party and has a relatively progressive political platform. Since his presidency, Obama continues to remain an influential figure, both in politics and pop culture. 

One factor that makes this comparison interesting is that both Kanye and Obama are politicians (to differing degrees). However, they have very different political ideologies, are in different phases of their careers, differ in personality, and differ in demographic characteristics (such as age). These characteristics influence the characteristics of their followers which may, in turn, influence the content of their tweets and how their followers engage with their tweets. Therefore, this may affect factors such as the timing, source, content, sentiment, and engagement level of their tweets. For this reason, our analysis aims to address the following question: can an algorithm based on tweet source, use of quotes, use of photos, and sentiment scores successfully predict whether a tweet was made by Barack Obama or Kanye West?


