---
title: "Methodology"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Twitter data from both Kanye West and Barack Obama was collected through a Twitter Developer account. After receiving a twitter API, tweets from both @kanyewest and @BarackObama were extracted from twitter in R Studio using the rtweet package. Other packages used to run models, manage and clean data, create visuals, text mine, run text analyses, and calculate statistics include: httpuv, tidytext, tidyverse, dplyr, lubridate, ggplot, scales, readr, syuzhet, mlbench, caret, vtreat, and InformationValue. 

Of all tweets posted, 3,200 tweets from both @BarackObama and @kanyewest were sampled randomly on April 21st, 2021. Dataframes containing the two sets of tweets were cleaned to only contain the source (which device the tweet was made on), status_id (ID of the tweet), text (text content of the tweet), created_at (time when tweet was created), retweet_count (number of retweets), favorite_count (number of favorites), is_retweet (whether or not the tweet is a retweet), and screen_name (screen name of the individual who tweeted it).

Prior to modeling, a number of summary statistics were calculated. To analyze differences in source of tweets, the count function was used to examine from which device both Kanye and Obama tweeted from most often. For time of day, the percent of total tweets sampled tweeted at each hour of the day was calculated for both Kanye and Obama and graphed as a line graph. Time tweeted was standardized using Eastern Standard Time (EST). Furthermore, the percentage of total tweets sampled starting with a quotation mark was calculated. Tendencies to include pictures or links in tweets was captured by calculating the total percentage of tweets containing either a picture, a link, or both among the tweets sampled. Furthermore, retweets and favorites were analyzed by calculating the percentage of tweets that are retweets out of the total sample, the average number of retweets on each of their tweets among the tweets sampled, and the average number of favorites on each of their tweets among the tweets sampled. Lastly, average sentiment for tweets were calculated for both Kanye and Obama. This was performed by removing all non-alphabetic characters using the str_replace_all command. Sentiment scores were calculated using the NRC Sentiment Dictionary. By running the command get_nrc_sentiment, sentiment scores were calculated for tweet texts. The average for both Kanye and Obama was then calculated for each of the following sentiments and valence: anticipation, fear, disgust, joy, sadness, surprise, trust, negative valence, and positive valence. Notably, percentages were used for comparisons because Kanye had fewer than 3,200 tweets while Obama had enough tweets to reach 3,200 sample tweets. Therefore, this was done to account for the difference in total number of tweets in the dataset for each person.

Multiple logistic regression was used to develop the predictive algorithm, using the glm function in R. The following predictors were included: whether the tweet uses a quotation mark, whether the tweet features a picture or link, and sentiment scores for the sentiments anticipation, fear, joy, trust, and positive valence. These factors were chosen due to a notable difference in behaviors observed between Kanye and Obama based on the summary statistics. The outcome variable was captured as being tweeted by Obama or not tweeted by Obama (i.e. tweeted by Kanye). The algorithms predictive power was then tested on a new set of tweets made by both Kanye and Obama. A train-test split was created with 70% of tweets from both Kanye and Obama included in the train set and 30% from each included in the test set.

Model diagnostics were calculated, including the optimal prediction probability cutoff, the misclassification error, the sensitivity level, and the specificity level. An AUC-ROC curve was created to demonstrate the ability to distinguish between the positive (i.e. Obama’s tweets) and negative class (i.e. Kanye’s tweet).

Lastly, the model was used on a set of tweets from an unrelated user. A random sample of 3,200 of Drake’s tweets (@Drake) run through the model. Examples of tweets by Drake that were classified as Obama and Kanye were then analyzed by examining how the characteristics of the tweets related to each component included in the model.
